version: "2"
services:
  my-app-1:
    container_name: "my-app-1"
    build: "."
    image: "node:latest"
    user: "node"
    working_dir: "/tp/2"
    volumes:
      - "/tp/2/:/tp/2"
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - "node-network"
    command: bash -c "npm install && node index.js"
  my-app-2:
    container_name: "my-app-2"
    build: "."
    image: "node:latest"
    user: "node"
    working_dir: "/tp/3"
    volumes:
      - "/tp/3:/tp/3"
    ports:
      - "8081:8081"
    expose:
      - "8081"
    networks:
      - "node-network"
    command: bash -c "npm install && node index.js"

networks:
  node-network:
    external: true